---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
notifications:
    - justin@dray.be
rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.0
env:
    - PUPPET_VERSION="3.6.0"
    - PUPPET_VERSION="3.7.0"
